# Generated by Django 6.1 on 2026-09-13 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeSpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('medium', models.CharField(choices=[('digital-art', 'Digital Art'), ('traditional', 'Traditional Art'), ('sketch', 'Sketch'), ('3d-model', '3D Model'), ('photography', 'Photography'), ('other', 'Other')], default='digital-art', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
