# Generated by Django 6.1 on 2026-09-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_creativespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativespace',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
